steps:
  - name: build
    image: docker:24.0.5-dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker buildx create --use
      - docker buildx build --push --platform linux/amd64,linux/arm64 -t sreeramdev/rust-docker-app:latest -f Dockerfile .

  - name: deploy
    image: docker:24.0.5
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull sreeramdev/rust-docker-app:latest
      - docker rm -f rust-container || true
      - docker run -d --name rust-container -p 2237:8080 sreeramdev/rust-docker-app:latest
